# Generated by Django 4.1.7 on 2023-05-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PelakuUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=100, null=True)),
                ('nib', models.CharField(max_length=100)),
                ('modal_kerja', models.IntegerField(blank=True, null=True)),
                ('laki_laki', models.IntegerField(blank=True, null=True)),
                ('perempuan', models.IntegerField(blank=True, null=True)),
                ('produksi', models.IntegerField(blank=True, null=True)),
                ('kapasistas', models.CharField(max_length=20, null=True)),
                ('nama_pelaku_usaha', models.CharField(max_length=100, null=True)),
                ('no_telp', models.CharField(max_length=100)),
            ],
        ),
    ]
