# Generated by Django 4.1.7 on 2023-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PelakuUsaha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelakuusaha',
            name='tanggal_input',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
