# Generated by Django 4.1.7 on 2023-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PelakuUsaha', '0002_pelakuusaha_tanggal_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelakuusaha',
            name='produksi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
