# Generated by Django 4.1.7 on 2023-05-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PelakuUsaha', '0003_alter_pelakuusaha_produksi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelakuusaha',
            old_name='kapasistas',
            new_name='kapasitas',
        ),
    ]
