# Generated by Django 4.1.7 on 2023-05-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PelakuUsaha', '0004_rename_kapasistas_pelakuusaha_kapasitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelakuusaha',
            name='tanggal_input',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
