# Generated by Django 4.2.1 on 2023-06-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PelakuUsaha', '0005_alter_pelakuusaha_tanggal_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelakuusaha',
            name='permasalahan',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
